### ISSUE TITLE
how can I get the ft8d result like WSJTX log format

### ISSUE THREAD

**Issue by d9394** [pavel-demin/ft8d#2]
Now I need the log to analyze , how can I get the log file list jt9 output format at redpitaya using your ft8d program?
215815 -5 1.1 1011 ~ EA1AHY K1HTV -15
215815 -8 1.0 1062 ~ VK4WTN DF9OX R-11
215815 -20 1.1 1155 ~ EK6RSC G1GIL R-04
215815 -6 0.6 1371 ~ YO2NAA K8YAH EN80
215815 -9 0.6 1421 ~ CQ IV3DXW JN65
215815 -7 1.2 1785 ~ CQ YI3WHR LM22
215815 1 0.2 2018 ~ CQ ON3BZ JO20
215815 -12 1.1 2094 ~ KB6IBB W4AS 73

**Comment by pavel-demin** [comment]
The output format is defined on [lines 84-86 in ft8d.f90](https://github.com/pavel-demin/ft8d/blob/master/ft8d.f90#L84-L86). So, to change the output format, these lines must be changed.

The current output format contains all the information required by the PSK reporter. Here is a link to the program that reads this format and sends the information to the PSK reporter: 
https://github.com/pavel-demin/red-pitaya-notes/blob/master/projects/sdr_transceiver_ft8/app/upload-to-pskreporter.c

**Comment by d9394** [comment]
Roger, I read the source of ft8d.f90 , but I don't understand what means of the variables.
And , another import things is : I have no environment to compile the source ╮(╯_╰)╭

**Comment by pavel-demin** [comment]
I think maybe more information on what is your setup and what you're trying to achieve would help me better understand the problem.

If you use this program on a Red Pitaya / STEMlab board, then the environment to build the FT8 decoder is already installed on the SD card. Here are the commands to rebuild the FT8 decoder:
```
apk add make gcc gfortran
lbu commit -d

cd /media/mmcblk0p1/apps/sdr_transceiver_ft8/ft8d
rw
make
ro
```

These commands should be run from the board's command line.

Depending on the type of the board, more information about the OS, logins, passwords, commands, etc can be found at the following links:
https://pavel-demin.github.io/red-pitaya-notes/alpine/
https://pavel-demin.github.io/stemlab-sdr-notes/alpine/

**Comment by d9394** [comment]
OK, I will try to modify "write" out of the source and recompile on my redpitaya.
thanks

**Comment by d9394** [comment]
rp-f04ed4:/media/mmcblk0p1/apps/sdr_transceiver_ft8/ft8d-master# apk add make gcc gfortran
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/armv7/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/armv7/APKINDEX.tar.gz
(1/10) Installing binutils (2.31.1-r2)
(2/10) Installing gmp (6.1.2-r1)
(3/10) Installing isl (0.18-r0)
(4/10) Installing libgomp (8.3.0-r0)
(5/10) Installing libatomic (8.3.0-r0)
(6/10) Installing mpfr3 (3.1.5-r1)
(7/10) Installing mpc1 (1.0.3-r1)
(8/10) Installing gcc (8.3.0-r0)
(9/10) Installing gfortran (8.3.0-r0)
 79% ######################################################################################################

when installing gfortran at 79%, the redpitaya hold , I try to ping it and reply time out.....
reboot also no reply
so, I only to rewrite the tf with system backup image.

**Comment by pavel-demin** [comment]
What is the model of your board? Is it 125-10, 125-14 or 122.88-16?

**Comment by pavel-demin** [comment]
I've just tried to install make, gcc and gfortran and to rebuild ft8d on my 125-14 board. It works without any problem.

If you have 125-10, then it's possible that the board doesn't have enough RAM. In this case, I can only suggest to have a look at [alpine.sh](https://github.com/pavel-demin/red-pitaya-notes/blob/master/scripts/alpine.sh) and try to exract the part that cross compiles the FT8 decoder.

**Comment by d9394** [comment]
Yes, I'm running a 125-10 redpitaya >:<

**Comment by d9394** [comment]
> 
> 
> I've just tried to install make, gcc and gfortran and to rebuild ft8d on my 125-14 board. It works without any problem.
> 
> If you have 125-10, then it's possible that the board doesn't have enough RAM. In this case, I can only suggest to have a look at [alpine.sh](https://github.com/pavel-demin/red-pitaya-notes/blob/master/scripts/alpine.sh) and try to exract the part that cross compiles the FT8 decoder.

Could you tell me which variable contain FT8 original message ,like this : 'KB6IBB W4AS 73"？

**Comment by pavel-demin** [comment]
The message is in `msg37(1:22)`. The corresponding format is `a22`.

**Comment by d9394** [comment]
OK, I had compiled ft8d on a 14bit redpitaya with source:
          write(*,1004) date,time,15*(ipart-1),min(sync,999.0),nint(xsnr), &
              xdt,nint(f1-2000+dialfreq),msg37(1:22),msggrid
1004      format(a6,1x,a4,i2.2,f6.1,i4,f6.2,i9,1x,a22,1x,a4)
