### ISSUE TITLE
how to start ft8-Decoder? how is the frontend?

### ISSUE THREAD

**Issue by mosesurban** [pavel-demin/ft8d#3]
Hello Pavel,

sorry for my beginner questions. I want to use your FT8 transceiver-software on my stemlab redpitaya 125-14.
I generated the alpine sd card how it is described. After booting in the RP, I see the main menue and choose the ft8 app. Now I see this, and how is it going on?

![grafik](https://user-images.githubusercontent.com/65852495/82766772-f03f2180-9e21-11ea-8b38-586028d701cc.png)

No app is starting. Do I need an wsjt-x program on my pc to receive the decoded ft8 messages from RP? Where do I find the frontend for the app?

many thx
Mathis

**Comment by pavel-demin** [comment]
Normally, the decoder is started automatically. If you followed the 'Configuring FT8 receiver' instructions and defined the CALL and GRID variables in upload-ft8.sh, then the decoded spots are automatically sent to pskreporter.

The frontend app is www.pskreporter.info.

**Comment by pavel-demin** [comment]
If you have other Red Pitaya related issues or questions, then please submit them to the [red-pitaya-notes repository](https://github.com/pavel-demin/red-pitaya-notes).
